Add copyright, fix config location, bump version to 1.7.7.1, fix exits

diff --git a/paramiko.SlackBuild b/paramiko.SlackBuild
--- a/paramiko.SlackBuild
+++ b/paramiko.SlackBuild
@@ -1,14 +1,31 @@
 #!/bin/sh
 #
-# SlackBuild for paramiko
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for Paramiko
+# Copyright (C) 2010,2012 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
+# $Id: paramiko.SlackBuild,v 1.2 2012/09/18 09:14:55 gsotirov Exp $
+#
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=paramiko
-VERSION=1.7.6
+VERSION=1.7.7.1
 BUILD=${BUILD:-1}
 ARCH=noarch
 
@@ -34,13 +51,13 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 3
 cd $SRC
 fix_source
 
 # Build & install
-python setup.py build || exit 1
-python setup.py install --root=$PKG || exit 2
+python setup.py build || exit 4
+python setup.py install --root=$PKG || exit 5
 
 # Prepare
 DOCFILES="$DOCFILES docs demos"
@@ -57,6 +74,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -64,6 +82,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Cleanup (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
